<?php
/** 
* Implements hook_form_alter
*/

function task_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
	if($form_id == 'system_site_information_settings'){
		 $form['actions']['submit']['#value'] = t('Update Configuration');
		// kint($form);die();	
} 
}

/** 
* Implements hook_uninstall
*/
function task_uninstall(){
    // Remove the previously set Site API Key configuration
    \Drupal::configFactory()->getEditable('siteapikey.configuration')->delete();
}

?>